(function () {
  const params = new URLSearchParams(location.search);
  const statuses = ["saved", "running", "applied", "failed"];
  const labels = { saved: "Saved", running: "In progress", applied: "Applied", failed: "Failed" };
  const frame = document.getElementById("gqo-live-frame");
  const overlay = document.getElementById("gqo-live-overlay");
  const key = `gqo-live:${location.pathname}:${params.get("actual") || ""}`;
  const state = { targetIds: [], hoverTargetId: "", editingId: "", filter: "all", collapsed: false, interaction: "review", items: load(), targets: [] };
  let drawFrame = 0;

  function byId(id) { return document.getElementById(id); }
  function actualUrl() { try { const url = new URL(params.get("actual") || ""); return ["http:", "https:"].includes(url.protocol) ? url.href : ""; } catch { return ""; } }
  function proxyUrl() { return "/__gqo/actual/"; }
  function page() { try { return new URL(actualUrl()).pathname.split("/").pop() || "actual"; } catch { return "actual"; } }
  function status(value) { if (["running", "applied", "failed"].includes(value)) return value; return "saved"; }
  function targetIds(item) { const ids = Array.isArray(item?.targetIds) ? item.targetIds : [item?.targetId]; return [...new Set(ids.filter(Boolean))]; }
  function normalize(items) { return Array.isArray(items) ? items.map((item) => ({ ...item, status: status(item.status), targetIds: targetIds(item) })) : []; }
  function load() { try { return normalize(JSON.parse(localStorage.getItem(key) || "[]")); } catch { return []; } }
  function writeStorage() { try { localStorage.setItem(key, JSON.stringify(state.items)); } catch {} }
  function doc() { try { return frame.contentDocument; } catch { return null; } }
  function win() { try { return frame.contentWindow; } catch { return null; } }
  function visible(element) { const rect = element.getBoundingClientRect(); const style = win().getComputedStyle(element); return rect.width > 0 && rect.height > 0 && rect.bottom >= 0 && rect.right >= 0 && rect.top <= win().innerHeight && rect.left <= win().innerWidth && style.visibility !== "hidden" && style.display !== "none"; }
  function targetElement(id) { return id && id !== "global" ? doc()?.querySelector(`[data-gqo-id="${CSS.escape(id)}"]`) : null; }
  function scopeFor(id) { if (id === "global") return "global"; return targetElement(id)?.getAttribute("data-gqo-scope") || "element"; }
  function inferName(element, id) { if (!element || id === "global") return "Global"; const explicit = element.getAttribute("aria-label") || element.getAttribute("title") || element.querySelector("h1,h2,h3,legend")?.textContent || targetText(element); const role = element.getAttribute("role") || element.tagName.toLowerCase(); return `${String(explicit || id).trim().replace(/\s+/g, " ").slice(0, 64)} · ${role}`; }
  function targetText(element) { const clone = element?.cloneNode(true); return (clone?.textContent || "").trim().replace(/\s+/g, " ").slice(0, 160); }
  function targetRecord(id) { const element = targetElement(id); const rect = id === "global" ? frame.getBoundingClientRect() : element?.getBoundingClientRect(); return { id, label: inferName(element, id), scope: scopeFor(id), editable: element?.getAttribute("data-gqo-editable") || "", text: id === "global" ? "" : targetText(element), bounds: rect ? { x: Math.round(rect.x), y: Math.round(rect.y), width: Math.round(rect.width), height: Math.round(rect.height) } : null }; }
  function discoverTargets() { const root = doc(); if (!root) return [targetRecord("global")]; const records = [...root.querySelectorAll("[data-gqo-id]")].filter(visible).map((element) => targetRecord(element.getAttribute("data-gqo-id") || "")).filter((target) => target.id); return [targetRecord("global")].concat(records); }
  function primaryTarget(ids) { return ids[0] || "global"; }
  function targetLabel(id) { return (state.targets.find((target) => target.id === id) || targetRecord(id)).label; }
  function targetSummary(ids) { return ids.map(targetLabel).join(" | "); }
  function compactTargetText(ids) { const first = targetLabel(ids[0] || "global"); return ids.length > 1 ? `${first} +${ids.length - 1}` : first; }
  function renderTargetChips(container, ids, removable = true) { container.textContent = ""; for (const id of ids) { const chip = document.createElement("span"); chip.className = "gqo-target-chip"; const record = state.targets.find((target) => target.id === id) || targetRecord(id); const text = document.createElement("span"); text.textContent = record.label; chip.append(text); if (removable) { const remove = document.createElement("button"); remove.type = "button"; remove.className = "gqo-target-chip-remove"; remove.textContent = "×"; remove.setAttribute("aria-label", `Remove ${record.label}`); remove.addEventListener("click", () => updateTargetSelection(state.targetIds.filter((targetId) => targetId !== id))); chip.append(remove); } container.append(chip); } }
  function selectedTargets() { return [...document.querySelectorAll("#gqo-target-menu input:checked")].map((input) => input.value); }
  function setSelectedTargets(ids) { for (const input of document.querySelectorAll("#gqo-target-menu input")) input.checked = ids.includes(input.value); updateTargetButton(ids); }
  function updateTargetButton(ids) { byId("gqo-target-button").textContent = compactTargetText(ids.length ? ids : ["global"]); }
  function updateStatusButton() { byId("gqo-status-button").textContent = state.filter === "all" ? "All" : labels[state.filter]; }
  function filteredItems() { return state.filter === "all" ? state.items : state.items.filter((item) => item.status === state.filter); }
  function changeRequests() { return state.items.filter((item) => item.type === "change-request"); }
  function requestFrom(item) { const ids = targetIds(item); return { id: item.id.replace(/^comment-/, "change-"), sourceCommentId: item.id, targetId: primaryTarget(ids), targetIds: ids, targetLabels: ids.map((id) => (state.targets.find((target) => target.id === id) || targetRecord(id)).label), targetSummary: targetSummary(ids), page: item.page, scope: ids.length > 1 ? "multi-target" : item.scope || scopeFor(primaryTarget(ids)), requestedChange: item.comment, rationale: "Captured from live visual review edit request.", acceptanceSignal: "Updated UI matches the requested live review change.", priority: item.severity, status: status(item.status), createdAt: item.createdAt, createdBy: "visual-review", savedAt: item.savedAt, savedBy: "visual-review", checks: { workStart: { targetConfirmed: true, requestActionable: true, scopeConfirmed: true, acceptanceSignalDefined: true, dependenciesRecorded: false }, completion: { artifactUpdated: false, acceptanceSignalObserved: false, documentsAligned: false, openQuestionsPreserved: true, changedArtifactsRecorded: false } } }; }
  function markdown() { const lines = ["# Visual Review Annotation Prompt", "", "Use these saved annotations as implementation input. Preserve unresolved items and update status only after work is verified.", ""]; for (const item of state.items) { const ids = targetIds(item); lines.push(`## ${targetSummary(ids)}`, "", `- Request ID: ${item.id}`, `- Targets: ${ids.join(", ")}`, `- Type: ${item.type}`, `- Severity: ${item.severity}`, `- Scope: ${ids.length > 1 ? "multi-target" : item.scope || scopeFor(primaryTarget(ids))}`, `- Status: ${status(item.status)}`, `- Page: ${item.page}`, `- Created: ${item.createdAt}`, "", "### Requested change", "", String(item.comment || "").replaceAll("`", "\\`"), "", "### Apply prompt", "", `Apply this UI change to ${ids.length > 1 ? "all listed targets" : "the listed target"}. Keep visual behavior outside the selected targets unchanged.`, ""); } return lines.join("\n"); }
  function syncPayload() { return { schema: "gqo.visual-review-state.v1", source: page(), actual: actualUrl(), savedAt: new Date().toISOString(), targets: state.targets, comments: state.items, changeRequests: { schema: "gqo.change-requests.v1", source: page(), actual: actualUrl(), exportedAt: new Date().toISOString(), requests: changeRequests().map(requestFrom) }, markdown: markdown() }; }
  function sync() { writeStorage(); fetch("/__gqo/save", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(syncPayload()) }).catch(() => {}); }
  function refresh() { fetch(`/__gqo/state?t=${Date.now()}`, { cache: "no-store" }).then((r) => r.ok ? r.json() : {}).then((payload) => { if (Array.isArray(payload.comments)) state.items = normalize(payload.comments); render(); }).catch(render); }
  function badge(value) { const span = document.createElement("span"); span.className = `gqo-status gqo-status-${status(value)}`; span.textContent = labels[status(value)]; return span; }
  function liveRect(id) { const element = targetElement(id); if (!element || !visible(element)) return null; const rect = element.getBoundingClientRect(); const frameRect = frame.getBoundingClientRect(); return { left: frameRect.left + rect.left, top: frameRect.top + rect.top, width: rect.width, height: rect.height }; }
  function activeTargetIds() { return [...new Set([state.hoverTargetId].concat(state.targetIds).filter((id) => id && id !== "global"))]; }
  function scheduleDraw() { if (drawFrame) return; drawFrame = requestAnimationFrame(() => { drawFrame = 0; drawOverlay(); }); }
  function updateTargets() { state.targets = discoverTargets(); const menu = byId("gqo-target-menu"); const selected = selectedTargets(); menu.textContent = ""; for (const target of state.targets) { const label = document.createElement("label"); label.className = "gqo-target-option"; const input = document.createElement("input"); input.type = "checkbox"; input.value = target.id; input.checked = selected.includes(target.id); input.addEventListener("change", () => updateTargetSelection(selectedTargets())); const text = document.createElement("span"); text.textContent = target.label; label.append(input, text); menu.append(label); } updateTargetButton(selected); scheduleDraw(); }
  function refreshStatusOptions() { const menu = byId("gqo-status-menu"); menu.textContent = ""; for (const option of ["all"].concat(statuses)) { const label = document.createElement("label"); label.className = "gqo-target-option"; const input = document.createElement("input"); input.type = "radio"; input.name = "gqo-status-filter"; input.value = option; input.checked = state.filter === option; input.addEventListener("change", () => { state.filter = option; updateStatusButton(); byId("gqo-status-menu").hidden = true; byId("gqo-status-button").setAttribute("aria-expanded", "false"); render(); scheduleDraw(); }); const text = document.createElement("span"); text.textContent = option === "all" ? "All" : labels[option]; label.append(input, text); menu.append(label); } updateStatusButton(); }
  function updateTargetSelection(ids) { state.targetIds = [...new Set(ids.filter(Boolean))]; setSelectedTargets(state.targetIds); renderTargetChips(byId("gqo-target-label"), state.targetIds); render(); scheduleDraw(); }
  function drawOverlay() { overlay.textContent = ""; for (const id of activeTargetIds()) { const rect = liveRect(id); if (!rect) continue; const box = document.createElement("div"); box.className = state.targetIds.includes(id) ? "gqo-live-target gqo-live-target-selected" : "gqo-live-target"; box.style.left = `${rect.left}px`; box.style.top = `${rect.top}px`; box.style.width = `${rect.width}px`; box.style.height = `${rect.height}px`; box.title = id; overlay.append(box); } renderLivePins(); }
  function renderLivePins() { const counts = new Map(); for (const item of filteredItems()) for (const id of targetIds(item).filter((targetId) => targetId !== "global")) counts.set(id, (counts.get(id) || 0) + 1); for (const [id, count] of counts) { const rect = liveRect(id); if (!rect) continue; const pin = document.createElement("button"); pin.type = "button"; pin.className = "gqo-comment-pin gqo-live-pin"; pin.textContent = String(count); pin.style.left = `${rect.left + rect.width - 10}px`; pin.style.top = `${rect.top - 10}px`; pin.addEventListener("click", (event) => { event.preventDefault(); event.stopPropagation(); openPanel([id]); }); overlay.append(pin); } }
  function createShell() { const toolbar = document.createElement("div"); toolbar.className = "gqo-toolbar"; toolbar.innerHTML = `<div class="gqo-toolbar-title"><strong>GIQO Live Review</strong><a href="${actualUrl()}" target="_blank" rel="noreferrer">Actual screen</a><span id="gqo-sync">Auto-save ready</span><span id="gqo-counts"></span></div><div class="gqo-toolbar-controls"><label class="gqo-picker-label">Status <span class="gqo-picker"><button id="gqo-status-button" type="button" aria-expanded="false">All</button><div id="gqo-status-menu" class="gqo-picker-menu" hidden></div></span></label><label class="gqo-target-picker-label">Target <span class="gqo-target-picker"><button id="gqo-target-button" type="button" aria-expanded="false">All</button><div id="gqo-target-menu" class="gqo-target-menu" hidden></div></span></label><span class="gqo-toolbar-actions"><button id="gqo-interaction" type="button" aria-pressed="true">Review clicks</button><button id="gqo-refresh" type="button">Refresh</button><button id="gqo-toggle" type="button" aria-expanded="true">Hide feedback</button></span></div>`; document.body.prepend(toolbar); refreshStatusOptions(); const panel = document.createElement("aside"); panel.className = "gqo-panel"; panel.hidden = true; panel.innerHTML = `<strong id="gqo-panel-title">GIQO edit request</strong><div id="gqo-target-label" class="gqo-target-chips"></div><label>Severity<select id="gqo-severity"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label><label>Request<textarea id="gqo-comment" placeholder="Write one requested UI change for the selected target(s)"></textarea></label><div class="gqo-panel-actions"><button id="gqo-cancel" type="button">Cancel</button><button id="gqo-save" type="button">Save</button></div>`; document.body.append(panel); const list = document.createElement("aside"); list.className = "gqo-comment-list"; list.innerHTML = `<div class="gqo-comment-list-header"><strong>Saved feedback</strong><button id="gqo-list-toggle" type="button" aria-expanded="true">Minimize</button></div><div id="gqo-comments"></div>`; document.body.append(list); return panel; }
  function openPanel(ids, item) { state.targetIds = targetIds(item || { targetIds: Array.isArray(ids) ? ids : [ids] }); state.editingId = item?.id || ""; setSelectedTargets(state.targetIds); byId("gqo-panel-title").textContent = item ? "Edit saved request" : "GIQO edit request"; renderTargetChips(byId("gqo-target-label"), state.targetIds); byId("gqo-severity").value = item?.severity || "low"; byId("gqo-comment").value = item?.comment || ""; document.querySelector(".gqo-panel").hidden = false; render(); scheduleDraw(); byId("gqo-comment").focus(); }
  function savePanel() { const ids = selectedTargets(); const comment = byId("gqo-comment").value.trim(); if (!ids.length || !comment) return; const now = new Date().toISOString(); const previous = state.items.find((item) => item.id === state.editingId); const next = { id: state.editingId || `comment-${Date.now()}`, targetId: primaryTarget(ids), targetIds: ids, targetLabels: ids.map((id) => (state.targets.find((target) => target.id === id) || targetRecord(id)).label), page: page(), mode: "edit", scope: ids.length > 1 ? "multi-target" : scopeFor(primaryTarget(ids)), type: "change-request", severity: byId("gqo-severity").value, comment, createdAt: previous?.createdAt || now, savedAt: now, status: previous?.status || "saved" }; state.items = previous ? state.items.map((item) => item.id === state.editingId ? next : item) : state.items.concat(next); state.editingId = ""; state.targetIds = ids; document.querySelector(".gqo-panel").hidden = true; sync(); render(); scheduleDraw(); }
  function editItem(id) { const item = state.items.find((entry) => entry.id === id); if (item) openPanel(targetIds(item), item); }
  function deleteItem(id) { state.items = state.items.filter((item) => item.id !== id); if (state.editingId === id) state.editingId = ""; sync(); render(); scheduleDraw(); }
  function renderCounts() { const counts = Object.fromEntries(statuses.map((value) => [value, state.items.filter((item) => item.status === value).length])); byId("gqo-counts").textContent = statuses.map((value) => `${labels[value]} ${counts[value]}`).join(" · "); }
  function renderList() { const box = byId("gqo-comments"); box.textContent = ""; const items = filteredItems(); if (!items.length) { const empty = document.createElement("p"); empty.className = "gqo-empty"; empty.textContent = state.filter === "all" ? "No saved edit requests." : "No saved requests match this status."; box.append(empty); } for (const item of items) { const ids = targetIds(item); const card = document.createElement("article"); card.className = "gqo-list-item"; const title = document.createElement("div"); title.className = "gqo-list-targets"; if (ids.length > 1) { const picker = document.createElement("div"); picker.className = "gqo-saved-target-picker"; const button = document.createElement("button"); button.type = "button"; button.textContent = compactTargetText(ids); const menu = document.createElement("div"); menu.className = "gqo-saved-target-menu gqo-target-chips"; menu.hidden = true; renderTargetChips(menu, ids, false); button.addEventListener("click", () => { menu.hidden = !menu.hidden; }); picker.append(button, menu); title.append(picker); } else { renderTargetChips(title, ids, false); } const body = document.createElement("p"); body.textContent = item.comment; const actions = document.createElement("div"); actions.className = "gqo-list-actions"; const edit = document.createElement("button"); edit.type = "button"; edit.textContent = "Edit"; edit.addEventListener("click", () => editItem(item.id)); const remove = document.createElement("button"); remove.type = "button"; remove.textContent = "Delete"; remove.addEventListener("click", () => deleteItem(item.id)); actions.append(edit, remove); card.append(title, body, badge(item.status), actions); box.append(card); } }
  function render() { renderCounts(); renderList(); document.body.dataset.gqoFeedbackCollapsed = state.collapsed ? "true" : "false"; document.body.dataset.gqoInteraction = state.interaction; }
  function setCollapsed(value) { state.collapsed = value; byId("gqo-toggle").textContent = value ? "Show feedback" : "Hide feedback"; byId("gqo-list-toggle").textContent = value ? "Show" : "Minimize"; render(); }
  function wire(panel) { byId("gqo-status-button").addEventListener("click", () => { const menu = byId("gqo-status-menu"); menu.hidden = !menu.hidden; byId("gqo-status-button").setAttribute("aria-expanded", String(!menu.hidden)); }); byId("gqo-target-button").addEventListener("click", () => { const menu = byId("gqo-target-menu"); menu.hidden = !menu.hidden; byId("gqo-target-button").setAttribute("aria-expanded", String(!menu.hidden)); }); document.addEventListener("click", (event) => { const target = event.target; if (target instanceof Element && !target.closest(".gqo-target-picker")) { byId("gqo-target-menu").hidden = true; byId("gqo-target-button").setAttribute("aria-expanded", "false"); } if (target instanceof Element && !target.closest(".gqo-picker")) { byId("gqo-status-menu").hidden = true; byId("gqo-status-button").setAttribute("aria-expanded", "false"); } }); byId("gqo-interaction").addEventListener("click", () => { state.interaction = state.interaction === "review" ? "interact" : "review"; byId("gqo-interaction").textContent = state.interaction === "review" ? "Review clicks" : "Interact with app"; byId("gqo-interaction").setAttribute("aria-pressed", String(state.interaction === "review")); render(); }); byId("gqo-refresh").addEventListener("click", () => { updateTargets(); refresh(); }); byId("gqo-toggle").addEventListener("click", () => setCollapsed(!state.collapsed)); byId("gqo-list-toggle").addEventListener("click", () => setCollapsed(!state.collapsed)); byId("gqo-cancel").addEventListener("click", () => { state.editingId = ""; panel.hidden = true; render(); scheduleDraw(); }); byId("gqo-save").addEventListener("click", savePanel); addEventListener("resize", scheduleDraw); frame.addEventListener("load", () => { updateTargets(); sync(); try { const root = doc(); const frameWindow = win(); const redraw = () => scheduleDraw(); root.addEventListener("mousemove", (event) => { const target = event.target.closest?.("[data-gqo-id]"); const nextId = target?.getAttribute("data-gqo-id") || ""; if (state.hoverTargetId !== nextId) { state.hoverTargetId = nextId; scheduleDraw(); } }, true); root.addEventListener("mouseleave", () => { state.hoverTargetId = ""; scheduleDraw(); }, true); root.addEventListener("scroll", redraw, true); frameWindow.addEventListener("resize", redraw); frameWindow.visualViewport?.addEventListener("resize", redraw); frameWindow.visualViewport?.addEventListener("scroll", redraw); new ResizeObserver(redraw).observe(root.documentElement); root.addEventListener("click", (event) => { if (state.interaction !== "review") return; const target = event.target.closest?.("[data-gqo-id]"); if (target) { event.preventDefault(); event.stopPropagation(); const id = target.getAttribute("data-gqo-id"); if (document.querySelector(".gqo-panel").hidden) openPanel([id]); else updateTargetSelection(state.targetIds.includes(id) ? state.targetIds : state.targetIds.concat(id)); } }, true); } catch {} }); }
  function init() { if (!actualUrl()) { document.body.textContent = "Missing --actual URL."; return; } const panel = createShell(); frame.src = proxyUrl(); wire(panel); refresh(); render(); }
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", init); else init();
})();
